### ISSUE TITLE
flutter-snippets doesn't show in Espanso Hub

### ISSUE THREAD

**Issue by smeech** [espanso/hub#114]
https://hub.espanso.org/calc-macos, the page linked to from the topmost item in https://hub.espanso.org/search?t=math just shows a blank page rather than the package page like the rest I have viewed.

**Comment by smeech** [comment]
Following my recent interventions `flutter-snippets` also doesn't have a page either.
Is it possible to reindex the hub?

**Comment by AucaCoyan** [comment]
>  Is it possible to reindex the hub?

Mmmm I don't know... possibly, but I need to investigate how

**Comment by smeech** [comment]
Maybe @arabello can help? He's done most of the recent [espanso/hub-frontend](https://github.com/espanso/hub-frontend) merges.

**Comment by arabello** [comment]
Hi guys, I gave it a quick look. My findings:
- There are two separated issues: `calc-macos` is [present](https://hub.espanso.org/calc-macos) with an empty page. The `flutter-snippets` has no page at all, but most importantly is not even present in the [hub release](https://github.com/espanso/hub/releases/download/v1.0.0/package_index.json) which `hub-frontend` gets the data from.
- `calc-macos` issue is at runtime, probably because something happen in the frontend and a top level component renders null. I will track this here https://github.com/espanso/hub-frontend/issues/43 . I am not sure this is related to the absence of tags anymore https://github.com/espanso/hub-frontend/issues/39: ignoring packages with no tags was a design choice and works at build time
- `flutter-snippets` case is curios as it seems that everything went throught: the package PR was merged > the `hub` [pipeline updated the release](https://github.com/espanso/hub/actions/runs/9670807680/job/26680233064) > the `hub` pipeline notified `hub-frontend` pipeline >  the `hub-frontend` [pipeline built and publish the new app](https://github.com/espanso/hub-frontend/actions/runs/9670826520/job/26680285735). Something broken, I guess during the second step and the new package might not have been considered for the new publication

I need more time to investigate both issues, I'll do it during the weekend and get back to you

**Comment by smeech** [comment]
Thank you.

**Comment by arabello** [comment]
For the `flutter-snippets` issue there was an inconsistency (I am not sure how) between #19 #117 #118 that causes the released hub's `package_index.json` to miss the `flutter-snippets` entry even if the package is present in the hub (files with manifest). The `hub-frontend` consequentially was built with no `flutter-snippets` page as it follows directly the `package_index.json` content.

The fastest mitigation is to run locally the [update_index](https://github.com/espanso/hub/blob/590647259a87dfacebbc6c5179dc1d2dc0976249/.github/scripts/publish_packages.py#L130-L163) routine only forcing env var `PUBLISH=true`. Permissions might be required to consent the `gh release upload` command. WDYT? I can give it a try.

Note that the index update routine is done only if there is missing packages between the released ones and the current state of the `hub`. This is why the last PR didn't trigger the index update. It might be considered to change the logic and let it updated anyway as it should have idempotent result.

**Comment by smeech** [comment]
A reindex is the obvious thing to try, to force the hub to align with the package repo. There could be other packages with blank pages anyway - `calc-macos` was just the one I came across.

"idempotent" is a new word for me!

**Comment by arabello** [comment]
I don't have write permission to release the new `package_index.json`. Maybe @AucaCoyan can help?

**Comment by arabello** [comment]
The `calc-macos` issue was investigated and tracked at https://github.com/espanso/hub-frontend/issues/43

**Comment by smeech** [comment]
Another one for the list: https://github.com/espanso/hub/pull/129

**Comment by AucaCoyan** [comment]
Solved in https://github.com/espanso/hub-frontend/pull/45 !
